spring:
  ai:
    dashscope:
      api-key: "TODO"
      workspace-id: "TODO"
      chat:
        options:
          model: "qwen-plus"
      speech-synthesis:
        options:
          model: "qwen-tts"
          voice: "Ethan"
      speech-recognize:
        options:
          model: "paraformer-8k-v2"
      interview:
        options:
          model: "qwen-max"

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: TODO
    username: TODO
    password: TODO

  data:
    redis:
      database: 1
      host: TODO
      port: 6379
      timeout: 5000
      password: TODO

